home:
    pattern:  /
    defaults: { _controller: NSSearchBundle:Common:index }
    requirements:
        _method:  GET

ns-article-search:
    pattern:  /article/list
    defaults: { _controller: NSSearchBundle:Article:list , page: 1 }
    requirements:
        _method:  GET

ns-article-search-paginated:
    pattern:  /article/list/{page}
    defaults: { _controller: NSSearchBundle:Article:list }
    requirements:
        _method:  GET

ns-article-export:
    pattern:  /article/export
    defaults: { _controller: NSSearchBundle:Article:export }
    requirements:
        _method:  GET

ns-article-stats:
    pattern:  /article/stats
    defaults: { _controller: NSSearchBundle:Article:stats }
    requirements:
        _method:  GET

ns-category-active:
    pattern:  /category/actives
    defaults: { _controller: NSSearchBundle:Category:listActives }
    requirements:
        _method:  GET
